### ISSUE TITLE
doesn't work on my forums

### ISSUE THREAD

**Issue by marposnar** [stevotvr/phpbb-groupsub#1]
Have tried with sandbox and without

Have tried changing versions of phpbb, tried 3.2.3, 3.2.4, 3.2.5.

Test purchases and sandbox purchases never show up in the transactions or subscriptions

Tried changing the cron from 1 hour to 1 minute to see if it would help add the transaction to the list, but nothing ever showed up even after disabling the extension, re-enabling, trying more types of purchases, etc.

Tried disabling all other extensions, using default style

No idea what else to try, really want to use this extension as I'm using another paid one right now called bbmembership that also has problems, but bbmembership works fine with some edits i've made as well as an autohotkey script for it that refreshes the groups for it every 5 minutes.

I couldn't find or didn't look long enough to see where or how this groupsub extension knows to add a new subscriber or how frequently it checks for new subcribers (is it that 1 hour cronjob?).

I hope you can help dad, I love you

**Comment by stevotvr** [comment]
Can you send me a link to your forum?

**Comment by marposnar** [comment]
Hello sir, I ended up going with bbmembership.  Their beta version of this is working insanely better than before.  My forums are just default phpbb 3.2.5 with a sql db.  Sorry cant link it here
