### ISSUE TITLE
Renewal for existing Subscription for Unlimited does not Update Expire time.

### ISSUE THREAD

**Issue by dark-1** [stevotvr/phpbb-groupsub#18]
The renewal for existing subscription for "Unlimited" does not update "Expire" time for that subscription.

How to reproduce :
1. The user did not use the sub's system , instead had transferred directly to PP account.
So I added that user to the sub via ACP.
2. When the "Expiry" time was near , the user used the "Renewal" button from sub's system using "Unlimited" option.
3. Transaction was successful but user's existing subscription's "Expire" time was not update for "Unlimited".

I hope you get this & understand what i mean.

BTW , when user has the "Unlimited" option , the "Subscriptions" list page only says "You are subscribed" instead of specifying like "You are subscribed for Unlimited".
Coz some users panicked , saying "what plan they are on ?"

Thanking you , Best regards 👍

**Comment by stevotvr** [comment]
Thanks for the bug report. I think I see what is causing that. I'll get it fixed as soon as I commit the addition I'm working on now.

**Comment by stevotvr** [comment]
I believe it is fixed now in the latest commit. I also added "forever" to the language line for unlimited subscriptions.

**Comment by dark-1** [comment]
Thank you very much. 😍 

Best regards 👍
