### ISSUE TITLE
User defined Max number of terms displayed as input type radio.

### ISSUE THREAD

**Issue by dark-1** [stevotvr/phpbb-groupsub#19]
Let user defined the Max number of terms displayed as input type radio.

At line : https://github.com/stevotvr/phpbb-groupsub/blob/master/styles/all/template/package_list.html#L60
```php
{% elseif p.term|length > 6 %}
```
replace the `6` with a variable.

Uses :
1. If the admin wants to display "more than 6" OR "less than 6" option as input type radio , then they can choose the same.
2. This will allow some granularity on that page.
3. This will also allow the forum user to clearly see more options & compare.
4. If you want you can implement per package bases. {Optional}
5. Default should be `6` , Min should be `2` & Max should be `99` or atleast `15`.

I hope you get me & understand it.
If more clarification required then let me know.

Thanking you , Best regards 👍

**Comment by stevotvr** [comment]
Sounds reasonable. I can add an option for that in the next version.

**Comment by dark-1** [comment]
Thank you very much. 😍 

Best regards 👍

**Comment by stevotvr** [comment]
Added in 7956e87

**Comment by dark-1** [comment]
Thanks 😍 

Work's like charm 😊 

Best regards 👍
