### ISSUE TITLE
More Notifications

### ISSUE THREAD

**Issue by dark-1** [stevotvr/phpbb-groupsub#20]
There is a need for : 
- [x] `Group Subscription begin notification` for user [A must & needed, just like `expired`] : 
  - There no notification when a subscription is started , the user see's this 
  - `Please allow a few minutes for your payment to be processed and your subscription to be activated.`
  - but does not see or get any confirmation when payment is processed and subscription is activated.
  - Hence this Notification.
 
- [x] User's `Group Subscription begin notification` for Admin [Optional] : 
  - This is Admin opted notification.
  - This can be toggled via `settings` module in ACP. simple `yes` or `no`.
  - Triggered along with the above mentioned `Group Subscription begin notification`.
  - useful to do some manual stuff , like : 
    - thanking the user.
    - in ACP , to do some stuff that require Admin's attention.
    - in Paypal , to do some stuff that require Admin's attention.
    - some other stuff...

I hope you get me & understand it.
Also I am hopping that this is not too much for you.
If more clarification required then let me know.

Thanking you , Best regards 👍

**Comment by stevotvr** [comment]
Added the first part: 430699b

**Comment by dark-1** [comment]
Thanks 😍

First part working as it should,
BUT I found that the Expire Notification doesn't get trigger when manually removed a subscription from a user.

By the above commit ,
there is a `stevotvr.groupsub.notification.type.started` in `add_subscription` function,
BUT none for `stevotvr.groupsub.notification.type.expired` in `end_subscription` function.

Also one more thing ,
I do not know what behavior it should be...
At : https://github.com/stevotvr/phpbb-groupsub/blob/1.2/operator/subscription.php#L373
and at : https://github.com/stevotvr/phpbb-groupsub/blob/1.2/operator/subscription.php#L479
You are removing the previous notifications , 
so should this `stevotvr.groupsub.notification.type.started` notification follow similar behavior ???

Best regards 👍

**Comment by stevotvr** [comment]
> First part working as it should,
> BUT I found that the Expire Notification doesn't get trigger when manually removed a subscription from a user.

I'll add a different notification for a cancelled subscription.

> Also one more thing ,
> I do not know what behavior it should be...
> At : https://github.com/stevotvr/phpbb-groupsub/blob/1.2/operator/subscription.php#L373
> and at : https://github.com/stevotvr/phpbb-groupsub/blob/1.2/operator/subscription.php#L479
> You are removing the previous notifications ,
> so should this `stevotvr.groupsub.notification.type.started` notification follow similar behavior ???

The expired notification replaces the warning notification. The other notifications should stay in the user's notification history,

**Comment by dark-1** [comment]
Ok.
Do as you think is best.

Also i have some more improvements, especially on administrator side, to make it more user friendly & useful to admins.
Should I make issues for them?

**Comment by stevotvr** [comment]
Yeah you should make a new issue if you have an idea.

I changed it so the warning and expire notifications will stay until the subscription is renewed. The notifications must be cleared before they can be sent again for the same item (subscription ID).

**Comment by dark-1** [comment]
Ok.

Thanking you , Best regards 👍

**Comment by stevotvr** [comment]
Added the second part mostly in 3715cc5
I still need to add the setting to toggle it. I might possibly create a custom permission or permissions for accessing different parts of the extension and receiving notifications.

**Comment by dark-1** [comment]
Ok....

Best regards 👍

**Comment by stevotvr** [comment]
I added the setting. I'll get to the custom permissions next.

**Comment by dark-1** [comment]
Nice 😍

Best regards 👍

**Comment by dark-1** [comment]
I'll test this & let you know soon....
this will take some time coz it has migration changes & i am a bit busy ...

Thanking you , Best regards 👍

**Comment by dark-1** [comment]
@stevotvr ,

i just tested this with commit : b7827bf3a80e83f39f11c3195cfec50f84a4aafe
& it works perfectly... Including the Migration FIX.

Sorry for Delayed Response.

Best regards :+1:

**Comment by stevotvr** [comment]
Thanks for taking the time to test this.
