### ISSUE TITLE
Ability to Re-Activate previous Subscription

### ISSUE THREAD

**Issue by dark-1** [stevotvr/phpbb-groupsub#21]
Reasons :
1. Since the "View" button in "View transactions" of ACP , redirects to the sub activated at that time,
& not the latest sub created by Admin manually.
2. Manually adding a new Sub with same data of old sub , re-activate the Old Sub.
3. Can be used to pause the sub for a user temporally by deactivating & then re-activating the same sub again.

I hope you get me & understand it.
If more clarification required then let me know.

Thanking you , Best regards 👍

**Comment by stevotvr** [comment]
This might require changes to some of the core functionality of the extension. I'll look into what would be required to implement this before deciding whether to add it to the next version.

**Comment by dark-1** [comment]
> This might require changes to some of the core functionality of the extension. I'll look into what would be required to implement this before deciding whether to add it to the next version.

My suggestion is to implement this in version after the next one, coz core of this extension needs to be tweaked...

Best regards 👍

**Comment by dark-1** [comment]
@stevotvr ,

Can you please tell me if this issue will be resolved in v1.2.0 ?

Thanking you , best regards 👍

**Comment by stevotvr** [comment]
I haven't had the chance yet to look at the details of how this would be implemented. I'll let you know as soon as I figure it out.

**Comment by dark-1** [comment]
Ho! Ok.
Thanks 😁

Best regards 👍

**Comment by stevotvr** [comment]
I don't think I will be making this change as requested. Instead, I could add a link on the subscription page to view a list of all of the user's subscriptions. This would make it easier to find the active subscription if one exists.

The reason I don't want to make the change you described is that it is a well established behavior of the extension and this would force the change on the existing users.

**Comment by dark-1** [comment]
> The reason I don't want to make the change you described is that it is a well established behavior of the extension and this would force the change on the existing users.

This doesn't change the existing behaviour, it's just add an additional feature.

Do you mind if I make a PR for it, so you can see what I mean.

Best regards 👍
