### ISSUE TITLE
Add the terms to Edit/Create Subscription

### ISSUE THREAD

**Issue by dark-1** [stevotvr/phpbb-groupsub#22]
I do not know how to express this in words , but I have made an Image for it : 
![0](https://user-images.githubusercontent.com/25451052/73190202-a08a6b00-414b-11ea-98ed-b0d25014f2eb.PNG)

This will reduce Admin's work of calculating the days & find exact date to end the sub, everytime while editing/creating many subs.

I hope you get me & understand it.
If more clarification required then let me know.

Thanking you , Best regards 👍

**Comment by stevotvr** [comment]
This would probably require some JavaScript to load the terms asynchronously. It might also be handy to have some kind of date picker for the field.

**Comment by dark-1** [comment]
> This would probably require some JavaScript to load the terms asynchronously. It might also be handy to have some kind of date picker for the field.

Loading the terms should be identical to subscription page via php but hidden.
Displaying only the the selected package terms.
For this you will need simple JavaScript or preferably jQuery to do the hidden & show effects.

Best regards 👍

**Comment by dark-1** [comment]
Hey !

any progress on this ???

Happy to help if required 😄 

Best regards 👍

**Comment by stevotvr** [comment]
Yeah I want to wait until the current version is approved or rejected by the phpBB team before continuing work on this.

**Comment by dark-1** [comment]
Ahh!!! Ok... No problem...
Even I am waiting for my 3 extentions to either be approved or rejected by phpBB CDB team.
This time they are taking quite long...
Best regards 👍

**Comment by stevotvr** [comment]
It's been approved! I'll get back to working on this some time this week.

**Comment by dark-1** [comment]
Ho! Nice ❤️ 

Best regards 👍

**Comment by stevotvr** [comment]
Added in 355e9e15bd8e927d5f885c399d1be3d2672c743f

**Comment by dark-1** [comment]
Thanks 😄 
I'll try this , give me some time , Please !!!

Best regards 👍

**Comment by dark-1** [comment]
Ok. I just tested this.

This work's when creating a new subscription but not when editing an old subscription.

Everything else is perfect 😊

Best regards 👍

**Comment by stevotvr** [comment]
> Ok. I just tested this.
> 
> This work's when creating a new subscription but not when editing an old subscription.

Fixed here: 843bae718a58e15149e292d17723e81f1276643a

**Comment by dark-1** [comment]
> Fixed here: [843bae7](https://github.com/stevotvr/phpbb-groupsub/commit/843bae718a58e15149e292d17723e81f1276643a)

Thanks 😘
This work's perfectly as expected. 😍

You may close this issue.

Thank you very much.😁
Best regards 👍
