### ISSUE TITLE
Add "Manage subscriptions" Mode to "User administration"

### ISSUE THREAD

**Issue by dark-1** [stevotvr/phpbb-groupsub#23]
I do not know how to express this in words , but I have made an Image for it : 
![1](https://user-images.githubusercontent.com/25451052/73192066-89994800-414e-11ea-86cd-9d43aee4d35a.png)

When too many subs are there by many users & also for same user ,
it becomes hard to find a particular Sub for a specific user.

This will solve that.

If you are at it , you may also want to add "View transactions" , If & only if you want to...

I hope you get me & understand it.
If more clarification required then let me know.

Thanking you , Best regards 👍

**Comment by dark-1** [comment]
BTW , I had done this before ,
this will require Migration file,
also if you need some Pseudo code , let me know...

Best regards 👍

**Comment by stevotvr** [comment]
This is something I considered doing from the beginning but decided to keep it in the Extensions tab. I'll add it to the user administration forms to add another entry point. It shouldn't be too difficult.

Sorry, I've been too busy to work on this the last few days.

**Comment by dark-1** [comment]
> Sorry, I've been too busy to work on this the last few days.

Take your time please...
No one's in hurry...

Best regards 👍

**Comment by stevotvr** [comment]
Added in 305c6e0
It testing and some refinement but it seems to work.

**Comment by dark-1** [comment]
@stevotvr ,

I am getting this error while trying to add a sub...
ERROR :
![1](https://user-images.githubusercontent.com/25451052/74420947-44755580-4e72-11ea-97b8-0c60cfe0a010.png)

Best regards 👍

**Comment by stevotvr** [comment]
Should be fixed in e22e5fd

**Comment by dark-1** [comment]
@stevotvr ,
sorry for late response ,
BUT tested with a1b198728a989e894bb0229d16dbb185ca85388a
& all is fine & perfect 👍 
Closing this issue.

BTW any plans on adding `View transactions` but on same mode/page of `Subscriptions` ??

Best regards 👍

**Comment by stevotvr** [comment]
I might add transactions to the page if I can figure out how to handle pagination. It might have to be on its own page to work properly. I might just add a link.
