### ISSUE TITLE
[3.3.0] Groups not assigning

### ISSUE THREAD

**Issue by PepoDance** [stevotvr/phpbb-groupsub#25]
Groups dont seem to be assign to users upon completion of purchase.

**Comment by stevotvr** [comment]
Can you provide more details? How do you have the package set up?

**Comment by PepoDance** [comment]
Is there anyway to contact you on Discord to show you an example?

**Comment by dark-1** [comment]
You can also upload images here...

Also latest version of groupsub have no problem with phpBB v3.3.0

Best regards 👍

**Comment by PepoDance** [comment]
Disregard, solved it.
