### ISSUE TITLE
paypal transactions not registering sometimes

### ISSUE THREAD

**Issue by marposnar** [stevotvr/phpbb-groupsub#26]
Sometimes the paypal payment will be made, but the transaction will now show up in the admin panel for groupsub, forcing me to add the user's subscription manually.

I usually have about 5-10 purchases a day so it's not that many, it seems like around 3 or 4 out of 10 will not be shown on the transaction list in the admin panel for groupsub.  Sometimes they appear later on.

Any ideas on what i should try?

I am using phpbb 3.2.5 and MySQL 5.6 and PHP 5.6.

Edit: seems like it might be my hosting servers sucking or paypals servers sucking but im not sure.  what do you think dad?

Please help or provide any advice or suggestions dad, I love you so much

**Comment by stevotvr** [comment]
Sometimes there can be a long delay before PayPal sends the notification. It can be really long if PayPal fails to connect to your server for some reason.
