### ISSUE TITLE
Add error logging 

### ISSUE THREAD

**Issue by margau** [stevotvr/phpbb-groupsub#29]
Hi,
thanks for this plugin!
I'm running 1.1.2 with phpBB 3.3.0.
I see IPN Requests in my access log, but all of them are answered with 400. The transaction table is empty. The PayPal transaction itself is successfull.

Is there any way to get debug output out of groupsub to know where the problem is?
Thanks!
margau

**Comment by margau** [comment]
I've found out the problem (#30) with placing many "error_logs" in the operator/transaction.php.

I wonder if there is more any elegant way to let the admin know where the processing of a transaction fails, as it is very black box at the moment. Would the usage of these error_logs be an option for upstream?

**Comment by stevotvr** [comment]
I'll look into adding some kind of logging to the extension.
