### ISSUE TITLE
Fatal error regarding "ocramius/proxy-manager" on phpBB 3.3.3

### ISSUE THREAD

**Issue by stevotvr** [stevotvr/phpbb-groupsub#36]
After upgrading to phpBB 3.3.3, this error appears. Running `composer require ocramius/proxy-manager` in the groupsub directory and purging the cache is a temporary solution.

> Got error 'PHP message: PHP Fatal error:  Uncaught OutOfBoundsException: Package "ocramius/proxy-manager" is not installed in /home/stevotvr/domains/dev.stevotvr.com/public_html/forum/ext/stevotvr/groupsub/vendor/composer/InstalledVersions.php:168\nStack trace:\n#0 /home/stevotvr/domains/dev.stevotvr.com/public_html/forum/vendor/composer/package-versions-deprecated/src/PackageVersions/Versions.php(112): Composer\\InstalledVersions::getPrettyVersion()\n#1 /home/stevotvr/domains/dev.stevotvr.com/public_html/forum/vendor/ocramius/proxy-manager/src/ProxyManager/Version.php(52): PackageVersions\\Versions::getVersion()\n#2 /home/stevotvr/domains/dev.stevotvr.com/public_html/forum/vendor/ocramius/proxy-manager/src/ProxyManager/Factory/AbstractBaseFactory.php(80): ProxyManager\\Version::getVersion()\n#3 /home/stevotvr/domains/dev.stevotvr.com/public_html/forum/vendor/ocramius/proxy-manager/src/ProxyManager/Factory/LazyLoadingValueHolderFactory.php(45): ProxyManager\\Factory\\AbstractBaseFactory->generateProxy()\n#4 /home/stevo...'

**Comment by 3D-I** [comment]
See: https://www.phpbb.com/customise/db/extension/groupsub/support/topic/227246?p=796421#p796421
