### ISSUE TITLE
Manually Add Users

### ISSUE THREAD

**Issue by ProjektPremium** [stevotvr/phpbb-groupsub#38]
Would it be possible to be able to manually add users through the ACP to a group and have it expire at a set date? This way I'm able to also manage people who donate by means other than PayPal.

Also, to add to that, hide the donate button but still be able to manage people into groups automatically.

**Comment by dark-1** [comment]
@ProjektPremium ,
it's already implemented , Do : 
- Go to ACP
- `Extensions` Tab
- Under `Group Subscription` header click on `Manage subscriptions`
- In `Manage subscriptions`, at bottom of your right hand on screen click button `Create subscription`
- Fill-up the `Create subscription` form with `Subscription details`
- click on button `Submit`
- Done, so enjoy 😃 

Now close this issue.

Best regards 👍

**Comment by ProjektPremium** [comment]
I'll give it a try. Thank you for your response. :)
