### ISSUE TITLE
Return(Thank You) Page for Unlimited Subscription gives 0 days/months/years

### ISSUE THREAD

**Issue by dark-1** [stevotvr/phpbb-groupsub#4]
The Return(Thank You) Page for Unlimited Subscription gives `0 days/months/years` instead of `Unlimited`.
For Example : 
![1](https://user-images.githubusercontent.com/25451052/61773210-c25c0b80-ae11-11e9-9249-c585ea50af0f.png)
Where it should be like : 
![2](https://user-images.githubusercontent.com/25451052/61773339-1535c300-ae12-11e9-9234-d2c975c1ea5f.png)
Similar to line : https://github.com/stevotvr/phpbb-groupsub/blob/master/styles/all/template/package_list.html#L46

Thanking you , Best regards 👍

**Comment by stevotvr** [comment]
Thanks for the report. That should be easy to fix.

**Comment by stevotvr** [comment]
Should it say 

> You have subscribed to **X** for **unlimited** time.

or

> You have started an **unlimited** subscription to **X**.

or something else?

**Comment by dark-1** [comment]
@stevotvr .

I think it's better to be first one , "You have subscribed to **X** for " , Coz it's common for all cases...
Just change "0 xxxx" to "Unlimited" , assuming you will add " time." at the end.

Else it's better to change this line : https://github.com/stevotvr/phpbb-groupsub/blob/master/language/en/common.php#L47
to "Lifetime", one word like before and specifically for time.

Thanking you, best regards 👍

**Comment by stevotvr** [comment]
Fixed in https://github.com/stevotvr/phpbb-groupsub/commit/c92d995a41ed179c5200512a7feef37069bee8c3

"Lifetime" might not be applicable to all situations so I think I'll leave it as "Unlimited."

**Comment by dark-1** [comment]
Ok... Thanks... 😄
