### ISSUE TITLE
Add Description for Subscribe Page.

### ISSUE THREAD

**Issue by dark-1** [stevotvr/phpbb-groupsub#5]
Add Description for Subscribe Page to put up some Information.
After line : https://github.com/stevotvr/phpbb-groupsub/blob/master/styles/all/template/package_list.html#L3
BUT before line : https://github.com/stevotvr/phpbb-groupsub/blob/master/styles/all/template/package_list.html#L5
similar to : **From** https://github.com/stevotvr/phpbb-groupsub/blob/master/styles/all/template/package_list.html#L78 **To** https://github.com/stevotvr/phpbb-groupsub/blob/master/styles/all/template/package_list.html#L86

Will require a `$config` to toggle this Description On/Off.
Also will require a `$config_text` to store this Description.

Hope you consider this Enhancement in your Extension.

Thanking you , Best regards 👍

**Comment by stevotvr** [comment]
So you want to add a text area to add some general information that isn't related to a specific subscription package? That sounds like a good idea. Thanks for the suggestion.

**Comment by dark-1** [comment]
@stevotvr ,

First of ... Thanks for the Extension... 😄 

Yea! Exactly... Adding some general Info & some details... 

Also if possible in the End also as footer to add some terms & conditions ,
maybe useful for many others also.

Best Regards 👍

**Comment by stevotvr** [comment]
Added header and footer options: https://github.com/stevotvr/phpbb-groupsub/commit/2661f62f80d30fdfd98cda2c34e6cbee693ecb9d

**Comment by dark-1** [comment]
Thank you very much @stevotvr 😄 👍
