### ISSUE TITLE
Switch to the new PayPal API

### ISSUE THREAD

**Issue by stevotvr** [stevotvr/phpbb-groupsub#6]
Replace the PayPal integration to use the new PayPal API. Possibly switch to use PayPal subscriptions if possible.

**Comment by dark-1** [comment]
Hey!!

With regards to this : 

> Create plans that charge users a fixed amount at regular intervals, or based on the quantity to which they subscribe.    

from https://developer.paypal.com/docs/subscriptions/
See that it's User select-able , that is , only if they want subscription without their interaction on regular intervals.
Also let them decide if one time subscription or regular subscription.

Thanking you , Best regards 👍

**Comment by stevotvr** [comment]
Sure, I'll try to make it an option if possible.

**Comment by dark-1** [comment]
Thanks... 😄

**Comment by stevotvr** [comment]
For security and ease of use, I think it would be best to stick with IPN. I'll open a new issue for adding a Subscribe button.

**Comment by dark-1** [comment]
Hmm! Ok... 👍
